spring:
  application:
    name: kyc-reports
  profiles:
    active: dev
  jackson:
    default-property-inclusion: NON_NULL

management:
  endpoints:
    web:
      exposure:
        include: info,health
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: false
    external-services:
      enabled: true
  info:
    build:
      enabled: false

kyc-config:
  reports:
    service-application: templates/KYC_SERVICE_FORM.pdf
    receipt: KYC_PAYMENT_RECEIPT #PATH RESOLVED BY SPRING BOOT, USING THYMELEAF
    contract: templates/KYC_CONTRACT.docx

kyc-messages:
  catalog:
    messages:
      "001":
        code: KYC-REPORTS-001
        message: Unexpected Error
        type: ERROR

logging:
  level:
    root: INFO
    com.kyc: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    #org.hibernate.type.descriptor.sql: TRACE
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE