spring:
  application:
    name: kyc-reports
  profiles:
    active: dev
  jackson:
    default-property-inclusion: NON_NULL

management:
  endpoints:
    web:
      exposure:
        include: info,health
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: false
    external-services:
      enabled: true
  info:
    build:
      enabled: false

kyc-config:
  reports:
    service-application: templates/KYC_SERVICE_FORM.pdf
    receipt: KYC_PAYMENT_RECEIPT #PATH RESOLVED BY SPRING BOOT, USING THYMELEAF
    contract: templates/KYC_CONTRACT.docx
    bill: templates/KYC_SERVICE_BILL.jasper

kyc-messages:
  catalog:
    messages:
      "001":
        code: KYC-REPORTS-001
        message: Unexpected Error
        type: ERROR
      "002":
        code: KYC-REPORTS-002
        message: The report could no be generated
        type: ERROR
      "003":
        code: KYC-REPORTS-003
        message: The report was not found or does not exists
        type: WARN
      "004":
        code: KYC-REPORTS-004
        message: The service is unavailable
        type: ERROR

logging:
  level:
    root: INFO
    com.kyc: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    #org.hibernate.type.descriptor.sql: TRACE
    net.sf.jasperreports: INFO
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE