spring:
  datasource:
    url: jdbc:postgresql://localhost:6000/kyc_database
    username: kyc_user
    password: kyc_pass
    hikari:
      maximum-pool-size: 1
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

eureka:
  client:
    enabled: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.100.61:9100/eureka

logging:
  level:
    root: INFO
    com.kyc: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    #org.hibernate.type.descriptor.sql: TRACE
    net.sf.jasperreports: INFO
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE